version: "3.9"
services:

  web-prd:
    image: "pysect-frontend-prd"
    container_name: pysect-frontend-prd
    environment:
      VIRTUAL_HOST: py.sect.letz.dev
      VIRTUAL_PATH: /
      VIRTUAL_PORT: 3000
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - nginx-reverse-proxy-net

networks:
  nginx-reverse-proxy-net:
    external: true